### ISSUE TITLE
Other Service Type?

### ISSUE THREAD

**Issue by DanielWeeber** [washcroft/homebridge-http-garagedoorcontroller#2]
Your plugin is working so well for me, I would like to say 1000x thanks to you. Magnificent plugin. Saved me LOTS of time.

I have only a (hopefully) small request. Is there any way to change the type from a garage door to a "normal" door? Everything else is working fine.

I'm using your plugin instead of a "normal door" one, because it's requesting the status right after you opened the door multiple times. I'm controlling a door buzzer (for my "normal" door) over that. The door buzzer is on for 4 seconds and your plugins displays that in homekit perfectly.

Its just a normal door, not a garage door ;)

**Comment by washcroft** [comment]
Hello,
Thanks for your feedback, I'm glad this project has helped others!

Is there another plugin with the service type that you're trying to emulate so that I can take a look at this for you? I'm not aware of another door type within HomeKit that has the opening/closing states the garage door has.

Best Regards

**Comment by DanielWeeber** [comment]
Hey,

thanks for the answer.
In the meantime I've forked you're project and edited everything to my needs.

I'm using Service.LockMechanism. This displays a "Lock Symbol", unfortunately not a "Door".
But this is working for me!

I'm not finished, yet - I need to remove the Light feature. But I'm glad it's working.

**Comment by washcroft** [comment]
Sorry for the delayed response! I'm glad you got it working.
